k = Kontakt
fs = Filesystem
inst = 0

-- USER SETUP ------------------------------------
-- END USER SETUP ------------------------------------

script = '{ Compiled on Sun Oct 13 16:57:42 2024 }\n'
script = script .. 'on init\n'
script = script ..   'declare $sksp_dummy\n'
script = script ..   'declare $concat_it\n'
script = script ..   'declare $concat_offset\n'
script = script ..   'declare $string_it\n'
script = script ..   'declare $list_it\n'
script = script ..   'declare $preproc_i\n'
script = script ..   'declare $i\n'
script = script ..   'declare $zone_id\n'
script = script ..   'declare $lowest_key := 127\n'
script = script ..   'declare $highest_key := 0\n'
script = script ..   'declare $low_key\n'
script = script ..   'declare $high_key\n'
script = script ..   '$i := 0\n'
script = script ..   'while ($i<get_num_zones())\n'
script = script ..     '$zone_id := get_zone_id($i)\n'
script = script ..     '$low_key := get_zone_par($zone_id,$ZONE_PAR_LOW_KEY)\n'
script = script ..     '$high_key := get_zone_par($zone_id,$ZONE_PAR_HIGH_KEY)\n'
script = script ..     'if ($low_key<$lowest_key)\n'
script = script ..       '$lowest_key := $low_key\n'
script = script ..     'end if\n'
script = script ..     'if ($high_key>$highest_key)\n'
script = script ..       '$highest_key := $high_key\n'
script = script ..     'end if\n'
script = script ..     'inc($i)\n'
script = script ..   'end while\n'
script = script ..   'declare %key_range[2]\n'
script = script ..   '%key_range[0] := $lowest_key\n'
script = script ..   '%key_range[1] := $highest_key\n'
script = script ..   'declare $num_ks\n'
script = script ..   'declare %ks_keys[32]\n'
script = script ..   'declare !ks_names[32]\n'
script = script ..   'declare @info_path\n'
script = script .. 'end on\n'
script = script .. 'on persistence_changed\n'
script = script ..   '$i := 0\n'
script = script ..   'while ($i<=127)\n'
script = script ..     'if (get_key_type($i)=$NI_KEY_TYPE_CONTROL)\n'
script = script ..       '%ks_keys[$num_ks] := $i\n'
script = script ..       '!ks_names[$num_ks] := get_key_name($i)\n'
script = script ..       'inc($num_ks)\n'
script = script ..     'end if\n'
script = script ..     'inc($i)\n'
script = script ..   'end while\n'
script = script ..   '@info_path := "C:/Users/Ben/My Drive/Kontakt/Kontakt API/Get nki info for Reaper/"\n'
script = script ..   'save_array_str(%key_range,@info_path & "key_range.nka")\n'
script = script ..   'save_array_str(%ks_keys,@info_path & "ks_keys.nka")\n'
script = script ..   'save_array_str(!ks_names,@info_path & "ks_names.nka")\n'
script = script .. 'end on\n'
k.set_instrument_script_source(inst, 4, script)
